baseURL = 'https://sam2008610.github.io'
languageCode = 'zh-tw'
title = '我的部落格'
theme = 'blowfish'

[params]
colorScheme = "slate"  # 使用深灰色配色方案
defaultColorScheme = "dark"  # 設定預設為深色模式
[params.author]
	name = "Livermor3"
description = "寫點東西"
layout = "grid"
showImage = true
defaultColorScheme = "auto"
links = [
  { github = "https://github.com/sam2008610" },
  { twitter = "https://x.com/Liv3rM0r3" },
]


[params.homeInfoParams]
	Title = "歡迎來到我的部落格"
	Content = "這裡是我分享想法和經驗的地方"

[params.header]
layout = "basic"

[params.homepage]
layout = "profile"
showRecent = true
showRecentItems = 6
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false

[params.article]
showDate = true
showAuthor = true
showReadingTime = false
showWordCount = false
  
[params.list]
showCards = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false
showTableOfContents = false

[params.term]
cardView = false
cardViewScreenWidth = false
showHero = false

[menu]
	[[menu.main]]
		name = "首頁"
		url = "/"
		weight = 1
	[[menu.main]]
		name = "文章"
		url = "/posts/"
		weight = 2
	[[menu.main]]
		name = "關於"
		url = "/about/"
		weight = 3